### ISSUE TITLE
Stomachs Dev

### ISSUE THREAD

**Issue by davjfish** [dfo-gulf-science/CADI#191]
### Things to consider for diets app:

- can we run a background script to harvest strata, latlong etc from oracle... maybe once per night or something..
- species table should be backended to CARL
- currently the "code" in diets is really the ID field. This is problematic.

To be discussed

**Comment by stoyelq** [comment]
Meeting outputs

- [ ] Make full db reports generate faster
- [ ] Add strata column to diets, provide Jenni with csv of mission_id's + sets to populate initial stratas, add stratas from andes
- [ ] Add new mission_ref_id field to cruises app, populate from cruise number as default, but match to Oracle in general, update 2004-2006 cruises
- [ ] Make prey dropdown regional codes only, add option to add a new regional code either from existing master catch or also make a new master catch
